### ISSUE TITLE
Not suitable for production

### ISSUE THREAD

**Issue by sirAlexander** [edwin/quarkus-secure-prometheus-api#1]
Not really a recommended approach for production. Quote from quarkus docs:

"Quarkus provides support for properties file based authentication that is intended for development and testing purposes. It is not recommended that this be used in production..."

**Comment by edwin** [comment]
hi, yes you are correct,
we can use below approach in order to make it more secure

```
https://quarkus.io/guides/security-jdbc
```

will create another example for that
